This is makeindex, version 2.16 [MiKTeX 24.4].
Scanning style file ./material.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file material.acn....done (3 entries accepted, 0 rejected).
Sorting entries....done (4 comparisons).
Generating output file material.acr....done (7 lines written, 0 warnings).
Output written in material.acr.
Transcript written in material.alg.
